---
title: "HW 09 - Bootstrapping the GSS"
author: "Team Awesome"
date: "2018-10-25"
output: github_document
---

### Load packages

```{r load-packages, message=FALSE}
library(infer)
library(tidyverse)
```

### Load data

```{r load-data, message=FALSE}
gss <- read_csv("gss2016.csv", guess_max = 1000)
```

### Set seed

```{r set-seed}
set.seed(12354)
```

(Add code chunks, exercise headings, and narrative as needed below.)

### Exercise 1

```{r}

```



### Exercise 2

```{r}

```

### Exercise 3

```{r}

```



### Exercise 4

```{r}

```

### Exercise 5

```{r}

```



### Exercise 6

```{r}

```

### Exercise 7

```{r}

```



### Exercise 8

```{r}

```

### Exercise 9

```{r}

```



### Exercise 10

```{r}

```

### Exercise 11

```{r}

```



### Exercise 12

```{r}

```

### Exercise 13

```{r}

```



### Exercise 14

```{r}

```

### Exercise 15

```{r}

```



### Exercise 16

```{r}

```

### Exercise 17

```{r}

```



### Exercise 18

```{r}

```

### Exercise 19

```{r}

```


